### ISSUE TITLE
Build Under Ubuntu

### ISSUE THREAD

**Issue by Yannnnnnnnnnnn** [nothinglo/NISwGSP#14]
I have made a cmake version of this project, maybe it will be helpful for guys who have no MAC.
https://github.com/Yannnnnnnnnnnn/NISwGSP

**Comment by nothinglo** [comment]
Thanks a lot!!!
I will add this information to the README.md.
Thanks again for your help!!!

**Comment by Yannnnnnnnnnnn** [comment]
I only check this code under Ubuntu16.04 and I will do more test to make sure it is okay.
