### ISSUE TITLE
How can I build this project in windows (MSVC 2015 specifically) 

### ISSUE THREAD

**Issue by ghost** [nothinglo/NISwGSP#16]
Someone help me plz. This project requires a lot of external libraries.

**Comment by firdauslubis88** [comment]
If you still need it, I have ported it to Visual Studio 15.7 (2017). I think it should work with VS2015 too. Please check it here:

https://github.com/firdauslubis88/NISwGSP.git

**Comment by nothinglo** [comment]
Thanks a lot to @firdauslubis88! I add your contribution to the README.md. Thanks for your kindness and help.
