### ISSUE TITLE
Build Under Visual Studio 15.7

### ISSUE THREAD

**Issue by firdauslubis88** [nothinglo/NISwGSP#17]
I have built the project under VS2017 15.7 here:

https://github.com/firdauslubis88/NISwGSP.git

I hope this will be useful. I have not done many tests, just try to run some examples and it seems fine until now. I will do more test later.

I also wanna thanks for the author for creating and sharing such awesome project 👍

**Comment by nothinglo** [comment]
Thanks a lot to @firdauslubis88! I add your contribution to the README.md. Thanks for your kindness and help.
