### ISSUE TITLE
A Problem Occured Whien Compiling

### ISSUE THREAD

**Issue by yuqing-liu-dut** [nothinglo/NISwGSP#19]
Hi, when I was following the steps from Yannnnnnnnnn, there is an error saying LINE_AA was not declared in this scope. So how should I solve it?

**Comment by nothinglo** [comment]
Maybe you can ask @Yannnnnnnnnn. Thanks.

**Comment by yuqing-liu-dut** [comment]
This problem is solved by using the OpenCV 3. Now I close this issue. Thanks the author.
