### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by hust0zzcc** [nothinglo/NISwGSP#2]
I met some problems when compiling your code.Can you tell me what is your code compilation environment?

**Comment by hust0zzcc** [comment]
Thank you very much for your reply.I compile the code in Windows and Linux,but I met some problems such as some variables are not defined.So I want to ask whether your project can be compiled in Windows or Linux,because I don't have IOS compilation environment.

**Comment by nothinglo** [comment]
I didn't compile the code in Windows or Linux before, but I think it should be ok. Could you tell me which variables are found undefined? Thanks.

**Comment by zyf12389** [comment]
MAXFLOAT  M_PI  M_PI_2 are not defined

**Comment by nothinglo** [comment]
You can define Pi and Pi^2 by yourself. Thanks.

**Comment by swq-1993** [comment]
Did you compiled the code in Linux successfully? @hust0zzcc , I met some problem just like you ever met , could you tell me you process and how do you fix it ?

**Comment by hust0zzcc** [comment]
I'm so sorry I missed your reply.My problem is as follows:'make_unique' was not declared in this scope in ImageData.cpp

**Comment by nothinglo** [comment]
Hi, I think you should check my compile information as below to make sure you can use some of the functions supported by the new version of C++.

My GCC_VRSION is Apple LLVM 6.0
```
GCC_C_LANGUAGE_STANDARD = GNU99 [-std=gnu99]
CLANG_CXX_LANGUAGE_STANDARD = GNU++14 [-std=gnu++14]
CLANG_CXX_LIBRARY = libc++ (LLVM C++ standard library with C++11 support)
```
Thanks.

**Comment by swq-1993** [comment]
sorry, I checked it . But I do not have MacOS , so I trying to set up your compile environment in my Ubuntu 16.04，now I met some problem in setting up the compile environment , so I need someone's help who compiled succeed the code.

**Comment by hust0zzcc** [comment]
I have downloaded LLVM 3.2 in Ubuntu 16.04,but I have never been in contact with it. I'm trying to compile your code using LLVM 3.2.
Thanks.

**Comment by hust0zzcc** [comment]
Hi!
I think maybe there is an error in your code at APAP_Stitching.cpp. V(j,V.rows()-1) should be V(j,cols()-1).Besides,Can you give me the download link of your Eigen version ?I can't find it.I can't use "LeastSquaresConjugateGradient" class successfully in Eigen 3.3.3,either.
Thanks!

**Comment by nothinglo** [comment]
Hi,

Indeed, it should be better to use cols(). I noticed it because the section of the code is followed by the APAP's author. I didn't change it because I think if it throws out the index error, it means your feature points are not enough (< 5). 

The Eigen's [main page](http://eigen.tuxfamily.org/) has the newest version [download link](http://bitbucket.org/eigen/eigen/get/default.zip) of the development branch. You can try it.

Thanks.

**Comment by hust0zzcc** [comment]
I have tried this version,but it still met the same error:
niswgsp: /usr/include/eigen3/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h:99: const Eigen::Solve<Eigen::DiagonalPreconditioner<_Scalar>, Rhs> Eigen::DiagonalPreconditioner<_Scalar>::solve(const Eigen::MatrixBase<OtherDerived>&) const [with Rhs = Eigen::Matrix<double, -1, 1>; _Scalar = double]: Assertion `m_invdiag.size()==b.rows() && "DiagonalPreconditioner::solve(): invalid number of rows of the right hand side matrix b"' failed.
I have no idea about how to solve this problem up to now.

**Comment by nothinglo** [comment]
Hi, 

Could you tell me this is a compile error or a runtime error?

Thanks.

**Comment by hust0zzcc** [comment]
It's a runtime error.

**Comment by nothinglo** [comment]
Hi, Could you give me more information like which file and which line did you get the error?
Thanks.

**Comment by codelgj** [comment]
@zyf12389 
hi, may I know your choices for MAXFLOAT?

**Comment by tlliao** [comment]
What's your choices for MAXFLOAT? In math.h, the M_PI_2 means half pi, so in your code, the M_PI_2 means square of pi, or half pi?

**Comment by tlliao** [comment]
What's your choices for MAXFLOAT? In math.h, the M_PI_2 means one-half pi, so in your code, the M_PI_2 means square of pi, or one-half pi?

**Comment by nothinglo** [comment]
@tlliao M_PI_2 == pi/2
Thanks.

**Comment by tlliao** [comment]
Hi, I find that the MAXFLOAT was used many times, so what's your choices for MAXFLOAT and what's the meaning?

**Comment by nothinglo** [comment]
It seems MAXFLOAT is not a standard parameter. You can change it as follow: https://stackoverflow.com/questions/28980541/error-identifier-maxfloat-is-undefined

In this project, it is used for initialization when finding the minimum number.

**Comment by cl199443** [comment]
Thanks for your source code ,which is important for me to learn image stitching. Besides, I have compiled and run this code  in Windows 10  successfully with VS2013.

**Comment by nothinglo** [comment]
@cl199443 

I am glad to get this news. If you have available time, maybe you can help me to reply some issues which fail to run the code? I will be really thankful to you!

**Comment by nothinglo** [comment]
Thanks to @Yannnnnnnnnnnn!
This is Ubuntu version:
https://github.com/Yannnnnnnnnnnn/NISwGSP
