### ISSUE TITLE
how does it happen?

### ISSUE THREAD

**Issue by huangshaoguang** [nothinglo/NISwGSP#20]
nThreads = 1
[#Images : 1]
i = 1, [Images : dataset25]
[ERROR] F(getImageFileFullNamesInDir) could not open directory
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
A = [2, 0]
NISwGSP: /usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:916: void Eigen::internal::set_from_triplets(const InputIterator&, const InputIterator&, SparseMatrixType&, DupFunctor) [with InputIterator = __gnu_cxx::__normal_iterator<Eigen::Triplet<double>*, std::vector<Eigen::Triplet<double> > >; SparseMatrixType = Eigen::SparseMatrix<double>; DupFunctor = Eigen::internal::scalar_sum_op<double>]: Assertion `it->row()>=0 && it->row()<mat.rows() && it->col()>=0 && it->col()<mat.cols()' failed.
Aborted (core dumped)

**Comment by nothinglo** [comment]
please refer to https://github.com/nothinglo/NISwGSP/issues/7. Thanks.

**Comment by huangshaoguang** [comment]
thanks for your reply...but I can't still run it...I compiled it in Ubuntu successfily. I download the input-42-data and unzip it in  NISwGSP.exe with the same path . I run it with the command line "sudo ./NISwGSP ./input-42-data/AANAP-building " and  it is wrong, and the wrong messages are:
nThreads = 1
[#Images : 1]
i = 1, [Images : dataset25]
[ERROR] F(getImageFileFullNamesInDir) could not open directory
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
A = [2, 0]
NISwGSP: /usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:916: void Eigen::internal::set_from_triplets(const InputIterator&, const InputIterator&, SparseMatrixType&, DupFunctor) [with InputIterator = __gnu_cxx::__normal_iterator<Eigen::Triplet*, std::vector<Eigen::Triplet > >; SparseMatrixType = Eigen::SparseMatrix; DupFunctor = Eigen::internal::scalar_sum_op]: Assertion `it->row()>=0 && it->row()<mat.rows() && it->col()>=0 && it->col()<mat.cols()' failed.
Aborted (core dumped)
how to solve it ? thanks a lot!

**Comment by huangshaoguang** [comment]
OK  I have sovled it! Thanks a lot!

**Comment by huangshaoguang** [comment]
hello, I have a new problem!I run on my dataset ，there is something wrong:
[#Images : 1]
i = 1, [Images : mycar]
Segmentation fault (core dumped)

what's the matter?

**Comment by nothinglo** [comment]
So you mean when running on the dataset I provided, there is no problem. But it has the error when running on your own dataset.

**Comment by huangshaoguang** [comment]
yes

**Comment by nothinglo** [comment]
Then I can only guess it should be the path issue.

**Comment by alexgoft** [comment]
> OK I have sovled it! Thanks a lot!

How did you solve it?

**Comment by alexgoft** [comment]
Sir, i still get the error @huangshaoguang got, and i dont understand how to solve it -

```
./NISwGSP /hdd/NISwGSP/UglyMan_NISwGSP_Stitching/UglyMan_NISwGSP_Stitching/build/input-42-data/SPHP-street 
nThreads = 1
[#Images : 1]
i = 1, [Images : /hdd/NISwGSP/UglyMan_NISwGSP_Stitching/UglyMan_NISwGSP_Stitching/build/input-42-data/SPHP-street]
[ERROR] F(getImageFileFullNamesInDir) could not open directory
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
[ERROR] F(getImagesMatchGraph) image match graph verification [2] didn't be implemented yet
A = [2, 0]
NISwGSP: /usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:916: void Eigen::internal::set_from_triplets(const InputIterator&, const InputIterator&, SparseMatrixType&, DupFunctor) [with InputIterator = __gnu_cxx::__normal_iterator<Eigen::Triplet<double>*, std::vector<Eigen::Triplet<double> > >; SparseMatrixType = Eigen::SparseMatrix<double>; DupFunctor = Eigen::internal::scalar_sum_op<double>]: Assertion `it->row()>=0 && it->row()<mat.rows() && it->col()>=0 && it->col()<mat.cols()' failed.
Aborted (core dumped)
```

**Comment by wl1085759633** [comment]
Hello, I have encountered this problem. How did you solve it?@ huangshaoguang

**Comment by yinsong-llsc** [comment]
> 好，我已经解决了！非常感谢！

我也遇到了同样的问题，请问一下是怎么解决的呢。非常感谢！

**Comment by RocketFlash** [comment]
Hi @huangshaoguang ! How did you solve the problem ?

**Comment by liqian-design** [comment]
Hi @huangshaoguang I have met the same problem,how did you solve it? Thanks.
