### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by winstonhong15** [nothinglo/NISwGSP#21]
I am new to Xcode and C++. I tried to compile this project in Xcode. I am running on macOS 10.13 with Xcode 9.4.1. I installed opencv 3.4.2 through Homebrew. I don't have openmp so I changed the code a little bit. Xcode suggested that there is error during the build process with error message: 

ld: library not found for -lopencv_adas.3.0.0
clang: error: linker command failed with exit code 1 (use -v to see invocation).

Ld /Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Products/Debug/UglyMan_NISwGSP_Stitching normal x86_64
    cd /Users/***/Downloads/NISwGSP-master/UglyMan_NISwGSP_Stitching
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Products/Debug -L/usr/local/lib -L/Users/***/Downloads/NISwGSP-master/UglyMan_NISwGSP_Stitching -L/Users/***/Downloads/NISwGSP-master/UglyMan_NISwGSP_Stitching/UglyMan_NISwGSP_Stitching/vlfeat-0.9.21/bin/maci64 -L/usr/local/Cellar -F/Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Products/Debug -filelist /Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Intermediates.noindex/UglyMan_NISwGSP_Stitching.build/Debug/UglyMan_NISwGSP_Stitching.build/Objects-normal/x86_64/UglyMan_NISwGSP_Stitching.LinkFileList -mmacosx-version-min=10.9 -Xlinker -object_path_lto -Xlinker /Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Intermediates.noindex/UglyMan_NISwGSP_Stitching.build/Debug/UglyMan_NISwGSP_Stitching.build/Objects-normal/x86_64/UglyMan_NISwGSP_Stitching_lto.o -Xlinker -no_deduplicate -stdlib=libc++ -liomp5 -lopencv_adas.3.0.0 -lopencv_adas.3.0.0 -lopencv_adas.3.0.0 -lopencv_bgsegm.3.0.0 -lopencv_bgsegm.3.0.0 -lopencv_bgsegm.3.0.0 -lopencv_bioinspired.3.0.0 -lopencv_bioinspired.3.0.0 -lopencv_bioinspired.3.0.0 -lopencv_calib3d.3.0.0 -lopencv_calib3d.3.0.0 -lopencv_calib3d.3.0.0 -lopencv_ccalib.3.0.0 -lopencv_ccalib.3.0.0 -lopencv_ccalib.3.0.0 -lopencv_core.3.0.0 -lopencv_core.3.0.0 -lopencv_core.3.0.0 -lopencv_datasets.3.0.0 -lopencv_datasets.3.0.0 -lopencv_datasets.3.0.0 -lopencv_face.3.0.0 -lopencv_face.3.0.0 -lopencv_face.3.0.0 -lopencv_features2d.3.0.0 -lopencv_features2d.3.0.0 -lopencv_features2d.3.0.0 -lopencv_flann.3.0.0 -lopencv_flann.3.0.0 -lopencv_flann.3.0.0 -lopencv_hal -lopencv_highgui.3.0.0 -lopencv_highgui.3.0.0 -lopencv_highgui.3.0.0 -lopencv_imgcodecs.3.0.0 -lopencv_imgcodecs.3.0.0 -lopencv_imgcodecs.3.0.0 -lopencv_imgproc.3.0.0 -lopencv_imgproc.3.0.0 -lopencv_imgproc.3.0.0 -lopencv_latentsvm.3.0.0 -lopencv_latentsvm.3.0.0 -lopencv_latentsvm.3.0.0 -lopencv_line_descriptor.3.0.0 -lopencv_line_descriptor.3.0.0 -lopencv_line_descriptor.3.0.0 -lopencv_ml.3.0.0 -lopencv_ml.3.0.0 -lopencv_ml.3.0.0 -lopencv_objdetect.3.0.0 -lopencv_objdetect.3.0.0 -lopencv_objdetect.3.0.0 -lopencv_optflow.3.0.0 -lopencv_optflow.3.0.0 -lopencv_optflow.3.0.0 -lopencv_photo.3.0.0 -lopencv_photo.3.0.0 -lopencv_photo.3.0.0 -lopencv_reg.3.0.0 -lopencv_reg.3.0.0 -lopencv_reg.3.0.0 -lopencv_rgbd.3.0.0 -lopencv_rgbd.3.0.0 -lopencv_rgbd.3.0.0 -lopencv_saliency.3.0.0 -lopencv_saliency.3.0.0 -lopencv_saliency.3.0.0 -lopencv_shape.3.0.0 -lopencv_shape.3.0.0 -lopencv_shape.3.0.0 -lopencv_stereo.3.0.0 -lopencv_stereo.3.0.0 -lopencv_stereo.3.0.0 -lopencv_stitching.3.0.0 -lopencv_stitching.3.0.0 -lopencv_stitching.3.0.0 -lopencv_superres.3.0.0 -lopencv_superres.3.0.0 -lopencv_superres.3.0.0 -lopencv_surface_matching.3.0.0 -lopencv_surface_matching.3.0.0 -lopencv_surface_matching.3.0.0 -lopencv_text.3.0.0 -lopencv_text.3.0.0 -lopencv_text.3.0.0 -lopencv_tracking.3.0.0 -lopencv_tracking.3.0.0 -lopencv_tracking.3.0.0 -lopencv_ts -lopencv_video.3.0.0 -lopencv_video.3.0.0 -lopencv_video.3.0.0 -lopencv_videoio.3.0.0 -lopencv_videoio.3.0.0 -lopencv_videoio.3.0.0 -lopencv_videostab.3.0.0 -lvl -lopencv_videostab.3.0.0 -lopencv_videostab.3.0.0 -lopencv_xfeatures2d.3.0.0 -lopencv_xfeatures2d.3.0.0 -lopencv_xfeatures2d.3.0.0 -lopencv_ximgproc.3.0.0 -lopencv_ximgproc.3.0.0 -lopencv_ximgproc.3.0.0 -lopencv_xobjdetect.3.0.0 -lopencv_xobjdetect.3.0.0 -lopencv_xobjdetect.3.0.0 -lopencv_xphoto.3.0.0 -lopencv_xphoto.3.0.0 -lopencv_xphoto.3.0.0 -Xlinker -dependency_info -Xlinker /Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Intermediates.noindex/UglyMan_NISwGSP_Stitching.build/Debug/UglyMan_NISwGSP_Stitching.build/Objects-normal/x86_64/UglyMan_NISwGSP_Stitching_dependency_info.dat -o /Users/***/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-hhiwctdecvbhimdppxzbugtfuybs/Build/Products/Debug/UglyMan_NISwGSP_Stitching

I am wondering what may be wrong with my setup? Thanks!

**Comment by nothinglo** [comment]
The most important message is:
1) ld: library not found for -lopencv_adas.3.0.0
2) clang: error: linker command failed with exit code 1 (use -v to see invocation).

You may need to change the setting in the Xcode project such as version or path. I used OpenCV 3.0.0 but you installed 3.4.2

**Comment by winstonhong15** [comment]
Thank you for your response. I did not notice that this xcode project required the specific OpenCV version. I changed it and I could build the project with xcode.
