### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by swq-1993** [nothinglo/NISwGSP#5]
I compiled the code in linux system,I follow the Usage , but I met some problem, I want to know your compiler and it's version, I use gcc-4.9, it reports  "/projects/NISwGSP_Stitching/Stitching/../Mesh/../Feature/../Mesh/Mesh2D.h:36:17: error: ‘class std::vector<int>’ has no member named ‘emplace_back’",it looks like the compiler issue , would you have linux version or can you tell me you compiler and it's version,Thanks!

**Comment by nothinglo** [comment]
Hi, 

I added my compile information as below:

GCC_VRSION is Apple LLVM 6.0
```
GCC_C_LANGUAGE_STANDARD = GNU99 [-std=gnu99]
CLANG_CXX_LANGUAGE_STANDARD = GNU++14 [-std=gnu++14]
CLANG_CXX_LIBRARY = libc++ (LLVM C++ standard library with C++11 support)
```

Thanks!
