### ISSUE TITLE
way of collecting the images

### ISSUE THREAD

**Issue by echozpz** [nothinglo/NISwGSP#6]
Hi, would you mind tell me the way you collected the images? By one camera or a multi-camera integrated device? If one, which kind of camera do you use?  Thank you.

**Comment by nothinglo** [comment]
Hi, we used only one handheld camera.
(just normal camera or you want to ask what camera brand?)

You can use any camera you like as long as you can make sure the feature points of images are suitable. Thanks.

**Comment by echozpz** [comment]
Thank you very much for your answer. Another question to bother you. Have you ever tried to stitch the images captured by fisheye lens, whose FOV may be larger than 180 degree?

**Comment by nothinglo** [comment]
Hi,

I didn't try the images whose FOV are significantly larger than the normal cameras'. My algorithm may not directly suitable for that case because the images in that setting are already distorted. It seems to me that you should make some modification if you want to stitch them.

Thanks.
