### ISSUE TITLE
Coud you write a more specify documents about the configures?

### ISSUE THREAD

**Issue by tribody** [nothinglo/NISwGSP#8]
I set up the project in xcode. But encounter an error like this "dyld: Library not loaded: /usr/local/opt/libiomp/lib/libiomp5.dylib
  Referenced from: /Users/riverhe/Library/Developer/Xcode/DerivedData/UglyMan_NISwGSP_Stitching-bhrpeieucbxnghfxqtdnsahboivz/Build/Products/Debug/UglyMan_NISwGSP_Stitching
"
what's wrong with this?

**Comment by nothinglo** [comment]
Hi, I forgot that I did use OpenMP (https://clang-omp.github.io).
You can follow the instructions in the "Using clang-omp with Xcode" section of the [link](https://clang-omp.github.io).
I added this instruction to the README.md.
Thanks!

**Comment by tribody** [comment]
Thanks, I do install it. And clang-omp is a subproject in llvm now. We should install llvm instead. The instructions can be found [there](https://stackoverflow.com/questions/38971394/brew-install-clang-omp-not-working). By the way, really thank you for your work and reply!

**Comment by nothinglo** [comment]
Wow, I didn't notice it. Really thanks for your reply. I will update the information in the README.md. Thanks!

**Comment by tribody** [comment]
I'm sorry to bother you again. Could you give a copy of ANAP code or just a link. I can't find a whole one online. THX!

**Comment by nothinglo** [comment]
Hi, I did send you an email. Thanks.

**Comment by tzxiang** [comment]
I'm sorry to bother you. Recently, I am learning the image stitching, including NISwGSP and ANAP. Could you offer a copy of ANAP code, I will be appreciated!

**Comment by nothinglo** [comment]
Hi, @tzxiang 

I sent the email to you. You can check. Thanks.

**Comment by nothinglo** [comment]
Hi, @tzxiang

I would like to send the email to you. But your email: tina2012zhu@gmail.com seems invalid. Could you offer your email? Thanks.

**Comment by tzxiang** [comment]
Hi, @nothinglo 
I am sorry. It's my fault. The email is wrong. The correct email is: tian2012zhu@gmail.com
Thank you very much!

**Comment by yyyph** [comment]
I am sorry to bother. NISwGSP shows that it is corrupted.Could you give a copy of NISwGSP code or just a link. I can't find a whole one online. THX

**Comment by nothinglo** [comment]
Hmmm it is still on GitHub: https://github.com/nothinglo/NISwGSP

yyyph <notifications@github.com> 於 2019年9月23日 週一 上午8:10寫道：

**Comment by yyyph** [comment]
It can be downloaded. But when unzipping it, the file display is damaged. Maybe it is my side of the problem. Thanks for your time. Could you offer a copy of ANAP code, If you have free time. I will be appreciated!

在 2019-09-23 16:19:41，"Yu-Sheng Chen" <notifications@github.com> 写道：
Hmmm it is still on GitHub: https://github.com/nothinglo/NISwGSP

yyyph <notifications@github.com> 於 2019年9月23日 週一 上午8:10寫道：
